### PR TITLE
Add in the option to disable empty tags

### PR DESCRIPTION
**Pull request by TRex22**
# What does this PR do?
- Bumps version
- Fixes some spelling mistakes
- Adds `allow_empty_tags` option

### CODE REVIEW

**Comment by jcubic** [comment]
Thanks for the PR, can you tell me what's the use of the new option? Is there a use case of adding empty tag? Maybe it should just always ignore empty tags.

**Comment by TRex22** [comment]
I wanted to keep the existing functionality 🤷‍♂️  .... we dont need it in our project. Im happy to remove the option and have it standard

**Comment by jcubic** [comment]
Yes, that would be great please remove the option and make ignore empty default. I would not bump feature version for this only bug fix, lowest number.

**Comment by TRex22** [comment]
Cool done 👍

**Comment by jcubic** [comment]
Great, one more request can you change the version to 0.2.2 it was kind of bug fix not the feature because there are no option now.

**Comment by TRex22** [comment]
Cool no problem

**Comment by TRex22** [comment]
Done

**Pull request merged**
