### PR TITLE
[feat]: add additional delimiters support for tag creation

### PR DESCRIPTION
**Pull request by Ashish-simpleCoder**
- Added support for ```additional_delimiters``` for creating new tags.
- Add type definitions for new parameter named ```additional_delimiters```.

### CODE REVIEW

**Comment by jcubic** [comment]
I would use the array `delimiters` which is set by default to `[',']` and I would remove `event.keyCode === 188`. Also, the type is wrong. It allows to only set semicolons. It should allow you to add any character as a delimiter.

**Comment by Ashish-simpleCoder** [comment]
If I set the default values for ```delimiters``` to ```[',']```, then it will overwritten when we initialize the ```tagger``` with new values for ```delimiters``` parameter.

**Comment by jcubic** [comment]
I think this is fine, the user will not add an additional delimiter only change it, which was the clue of the task.

You could merge the user settings with defaults but I don't think it will be a good idea in this case. If the user will like to have both `;` and `,` then he will need to use `delimiter: [',', ';']`. This can be added to README.

**Comment by Ashish-simpleCoder** [comment]
Should I update the code or just leave it as it is now?
Pls guide me.

**Comment by jcubic** [comment]
If you want your PR to be merged please follow my guide in the comments and modify the code accordingly.

I prefer to have an option that allows to set the delimiter. Also if you can update README with a new option that would be great.

**Comment by jcubic** [comment]
I don't see any update from the author to fix what is needed. So I'm closing the PR.

**Pull request closed without merging**
